<?php

return [
    'id'        => 'mission',
    'name'      => __('Mission'),
    'icon'      => '<i class="icon-globe"></i>',
    'tab'       => 'Common',
    'fields'    => [
        [
            'id'            => 'pre_heading',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('Pre Heading'),
            'placeholder'   => __('Enter pre heading'),
        ],
        [
            'id'            => 'heading',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('Heading'),
            'placeholder'   => __('Enter heading'),
        ],
        [
            'id'            => 'paragraph',
            'type'          => 'editor',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('Description'),
            'placeholder'   => __('Enter description'),
        ],
        [
            'id'                => 'list_data',
            'type'              => 'repeater',
            'label_title'       => __('List data'),
            'repeater_title'    => __('List data'),
            'multi'             => true,
            'fields'        => [
                [
                    'id'            => 'item_heading',
                    'type'          => 'text',
                    'value'         => '',
                    'class'         => '',
                    'label_title'   => __('Item heading'),
                    'placeholder'   => __('Enter heading'),
                ],
                [
                    'id'            => 'list_item',
                    'type'          => 'text',
                    'value'         => '',
                    'class'         => '',
                    'label_title'   => __('List items'),
                    'placeholder'   => __('Enter item'),
                ],
            ]
        ],
        [
            'id'            => 'mission_frame_image',
            'type'          => 'file',
            'class'         => '',
            'label_title'   => __('Frame image'),
            'label_desc'    => __('Add image'),
            'max_size'      => 4,
            'ext'    => [
                'jpg',
                'png',
                'svg',
            ],
        ],
        [
            'id'            => 'user_one_image',
            'type'          => 'file',
            'class'         => '',
            'label_title'   => __('First user image'),
            'label_desc'    => __('Add image'),
            'max_size'   => 4,
            'ext'    => [
                'jpg',
                'png',
                'svg',
            ],
        ],
        [
            'id'            => 'handshake_image',
            'type'          => 'file',
            'class'         => '',
            'label_title'   => __('Image'),
            'label_desc'    => __('Add image'),
            'max_size'   => 4,
            'ext'    => [
                'jpg',
                'png',
                'svg',
            ],
        ],
        [
            'id'            => 'user_two_image',
            'type'          => 'file',
            'class'         => '',
            'label_title'   => __('Second user image'),
            'label_desc'    => __('Add image'),
            'max_size'   => 4,
            'ext'    => [
                'jpg',
                'png',
                'svg',
            ],
        ],
        [
            'id'            => 'image_heading',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('Image heading'),
            'placeholder'   => __('Enter heading'),
        ],
        [
            'id'            => 'courses_text',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('Courses text'),
            'placeholder'   => __('Enter text'),
        ],
    ]
];
