<?php

return [
    'id'        => 'categories',
    'name'      => __('Categories'),
    'icon'      => '<i class="icon-clipboard"></i>',
    'tab'       => "Common",
    'fields'    => [
          [
            'id'            => 'categories_verient',
            'type'          => 'select',
            'class'         => '',
            'label_title'   => __('Select verient'),
            'options'       => [
                'verient-one'        => 'Verient one',
                'verient-two'        => 'Verient two',
            ],
            'default'       => 'non',  
            'placeholder'   => __('Select from the list'),  
        ],
        [
            'id'            => 'pre_heading',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('Pre heading'),
            'placeholder'   => __('Enter pre heading'),
        ],
        [
            'id'            => 'heading',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('Heading'),
            'placeholder'   => __('Enter heading'),
        ],
        [
            'id'            => 'paragraph',
            'type'          => 'editor',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('Description'),
            'placeholder'   => __('Enter description'),
        ],
        [                                                          
            'id'                => 'categories_repeater',
            'type'              => 'repeater',
            'label_title'       => __('Categories'),
            'repeater_title'    => __('Add category'),
            'multi'             => true,
            'fields'       => [
                [
                    'id'            => 'category_image',
                    'type'          => 'file',
                    'class'         => '',
                    'label_title'   => __('Category image'),
                    'label_desc'    => __('Add image'),
                    'max_size'      => 4,                  
                    'ext'    => [
                        'jpg',
                        'png',
                        'svg',
                    ], 
                ],
                [
                    'id'            => 'category_heading',
                    'type'          => 'text',
                    'value'         => '',
                    'class'         => '',
                    'label_title'   => __('Heading'),
                    'placeholder'   => __('Enter heading'),
                ],
                [
                    'id'            => 'category_paragraph',
                    'type'          => 'editor',
                    'value'         => '',
                    'class'         => '',
                    'label_title'   => __('Description'),
                    'placeholder'   => __('Enter description'),
                ],
                [
                    'id'            => 'explore_more_btn_url',
                    'type'          => 'text',
                    'value'         => '',
                    'class'         => '',
                    'label_title'   => __('Explore more button URL'),
                    'placeholder'   => __('Enter url'),
                ],
                [
                    'id'            => 'explore_more_btn_txt',
                    'type'          => 'text',
                    'value'         => '',
                    'class'         => '',
                    'label_title'   => __('Explore more button text'),
                    'placeholder'   => __('Enter button text'),
                ],
            ]
        ],
        [
            'id'            => 'all_category_heading',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('All category heading'),
            'placeholder'   => __('Enter heading'),
        ],
        [
            'id'            => 'all_category_paragraph',
            'type'          => 'editor',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('All category Description'),
            'placeholder'   => __('Enter description'),
        ],
        [
            'id'            => 'view_category_btn_url',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('View category button URL'),
            'placeholder'   => __('Enter url'),
        ],
        [
            'id'            => 'view_category_btn_txt',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('View category button text'),
            'placeholder'   => __('Enter button text'),
        ],
    ]
];
